server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/huang_test_01?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

